-- create a database "movie1" if not exists
create database if not exists movie1;

-- select your user
use deniz_goez;

-- define schema for the movie1 table
create table movie1 (
		index string,
		user_id string,
		tweet string,
		retweets string,
		location string,
		created string,
		followers int, 
		keyword string,
		language string)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
tblproperties("skip.header.line.count"="1");
LOCATION '/user/deniz_goez/project/to_hive_aftercorona.csv/';